name: Build

on: [push, pull_request]

jobs:
  linux:
    name: Build (${{ matrix.os }}) - ${{ matrix.conf }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        conf: [Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}
          -D GOOGLETEST=ON
          -D BUILD_TESTING=OFF
          -D client=OFF
          -D device=OFF
          -D gena=OFF
          -D ipv6=OFF
          -D optssdp=OFF
          -D samples=OFF
          -D scriptsupport=OFF
          -D soap=OFF
          -D ssdp=OFF
          -D tools=OFF

      - name: Build
        run: cmake --build build
