name: CI ctests

on:
  push:
    branches: [ dev, gtests, workflow_dispatch ]
  pull_request:
    branches: [ dev, gtests, workflow_dispatch ]

jobs:
  # Job: Run gtests
  #----------------
  Run_gtests:
    name: Run gtests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ ubuntu-latest, macOS-10.15, macOS-latest, windows-2016, windows-latest ]
        os: [ ubuntu-latest, macOS-10.15, macOS-latest, windows-latest ]
        shared: [ '', '-D BUILD_SHARED_LIBS=ON' ]
      fail-fast: false

    steps:
    # Step building gtests
      - uses: actions/checkout@v2

      # windows-2016 is deprecated. With newer versions pthread functions are not found
      # on compiling. Seems pthreads4w has problems with 32 bit platforms on newer
      # versions. I don't take any effort to fix this because it is intended to use
      # C++ multithreading functions instead.
      #- if: matrix.os == 'windows-2016'
      #  name: Use MS Windows 32 bit
      #  uses: ilammy/msvc-dev-cmd@v1
      #  with:
      #    arch: win32

      - if: matrix.os == 'windows-latest'
        name: Use MS Windows 64 bit
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure
        run: cmake -S . -B build -D UPNPLIB_WITH_GOOGLETEST=ON ${{matrix.shared}} -D CMAKE_BUILD_TYPE=MinSizeRel

      - name: Build
        run: cmake --build build --config MinSizeRel

      - if: runner.os != 'Windows'
        name: Run gtests not on MS Windows
        run: |
          cd ./gtests/build
          ctest --output-on-failure

      - if: runner.os == 'Windows'
        name: Run gtests on MS Windows
        run: |
          cd ./gtests/build
          ctest -C MinSizeRel --output-on-failure

  # Job: Run build tests
  #---------------------
  Run_build_tests:
    name: Run build tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-10.15, macOS-latest, windows-latest ]
        shared: [ '', '-D BUILD_SHARED_LIBS=ON' ]
      fail-fast: false

    steps:
    # Step building tests
      - uses: actions/checkout@v2

      # See note at previous job.
      #- if: matrix.os == 'windows-2016'
      #  name: Use MS Windows 32 bit
      #  uses: ilammy/msvc-dev-cmd@v1
      #  with:
      #    arch: win32

      - if: matrix.os == 'windows-latest'
        name: Use MS Windows 64 bit
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=MinSizeRel

      - name: Build
        run: cmake --build build --config MinSizeRel

      - name: Run build tests
        run: |
          cd ./build
          # --build-config is needed for MS Windows but ignored.
          # The settings within the test source are used.
          ctest --build-config Release --output-on-failure --stop-on-failure
