name: CI Linux
# ubuntu-18.04 isn't used for tests because it doesn't support open standard
# ISO C++20 that we declared to use for UPnPlib.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job: Configure and build
  #-------------------------
  Configure_and_build:
    name: Configure and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        googletest: [ '', '-D UPNPLIB_WITH_GOOGLETEST=ON' ]
        shared: [ '', '-D BUILD_SHARED_LIBS=ON' ]
        buildtype: [ 'MinSizeRel', 'Debug' ]
          # Possible old options from pupnp
          # -D CMAKE_BUILD_TYPE=MinSizeRel
          # -D client=OFF
          # -D device=OFF
          # -D gena=OFF
          # -D ipv6=OFF
          # -D optssdp=OFF
          # -D samples=OFF
          # -D scriptsupport=OFF
          # -D soap=OFF
          # -D ssdp=OFF
          # -D tools=OFF
      fail-fast: false

    steps:
    # Step building the core upnplib
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S . -B build ${{matrix.googletest}} ${{matrix.shared}} -D CMAKE_BUILD_TYPE=${{matrix.buildtype}}

      - name: Build
        run: cmake --build build --config ${{matrix.buildtype}}

      - if: (matrix.googletest == '-D UPNPLIB_WITH_GOOGLETEST=ON') && (matrix.shared == '') && (matrix.buildtype != 'Debug')
        name: Check gtest library files, static, NOT Debug
        run: |
          ls ./build/lib/libgtest.a
          ls ./build/lib/libgmock.a
          ls ./build/lib/libgtest_main.a
          ls ./build/lib/libgmock_main.a

      - if: (matrix.googletest == '-D UPNPLIB_WITH_GOOGLETEST=ON') && (matrix.shared == '') && (matrix.buildtype == 'Debug')
        name: Check gtest library files, static, Debug
        run: |
          ls ./build/lib/libgtestd.a
          ls ./build/lib/libgmockd.a
          ls ./build/lib/libgtest_maind.a
          ls ./build/lib/libgmock_maind.a

      - if: (matrix.googletest == '-D UPNPLIB_WITH_GOOGLETEST=ON') && (matrix.shared == '-D BUILD_SHARED_LIBS=ON') && (matrix.buildtype != 'Debug')
        name: Check gtest library files, shared, NOT Debug
        run: |
          ls ./build/lib/libgtest.so
          ls ./build/lib/libgmock.so
          ls ./build/lib/libgtest_main.so
          ls ./build/lib/libgmock_main.so

      - if: (matrix.googletest == '-D UPNPLIB_WITH_GOOGLETEST=ON') && (matrix.shared == '-D BUILD_SHARED_LIBS=ON') && (matrix.buildtype == 'Debug')
        name: Check gtest library files, shared, Debug
        run: |
          ls ./build/lib/libgtestd.so
          ls ./build/lib/libgmockd.so
          ls ./build/lib/libgtest_maind.so
          ls ./build/lib/libgmock_maind.so

      - if: matrix.googletest == '-D UPNPLIB_WITH_GOOGLETEST=ON'
        name: Run simple gtest
        # This gtest is always built with GoogleTest
        run: ./gtests/build/test_simple

      - if: matrix.buildtype != 'Debug'
        name: Verify if NO Debug info
        # These two libraries are always built
        run: |
          objdump -g pupnp/upnp/build/lib/libupnplib.so | grep --ignore-case --max-count=1 --invert-match "Contents of the .debug_info section"
          ls pupnp/upnp/build/lib/libupnplib.a

      - if: matrix.buildtype == 'Debug'
        name: Verify if Debug info
        # These two libraries are always built
        run: |
          objdump -g pupnp/upnp/build/lib/libupnplib.so | grep --ignore-case --max-count=1 "Contents of the .debug_info section"
          ls pupnp/upnp/build/lib/libupnplib.a

      - name: Run upnplib info program
        # This program is always built
        run: ./pupnp/upnp/build/upnplibInfo
