name: Check clang format

on: [ push, pull_request, workflow_dispatch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './upnp ./ixml ./gtests'
        extensions: 'cpp'
        clangFormatVersion: 12
