name: Build for MS Windows

on: [push, pull_request]

jobs:
  windows:
    name: Build (${{ matrix.os }})  - ${{ matrix.conf }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2016, windows-2019]
        conf: [Debug, Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure upnplib
        run: >
          cmake
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}

      - name: Build upnplib
        run: cmake --build build
