name: Builds for Unix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    name: Job build (${{ matrix.os }}) - ${{ matrix.conf }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        conf: [Debug, Release]
      fail-fast: false

    steps:
    # Step building the core upnplib
      - uses: actions/checkout@v2

      - name: Configure core upnplib
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.conf }}
#          -D GOOGLETEST=ON
#          -D BUILD_TESTING=OFF
#          -D client=OFF
#          -D device=OFF
#          -D gena=OFF
#          -D ipv6=OFF
#          -D optssdp=OFF
#          -D samples=OFF
#          -D scriptsupport=OFF
#          -D soap=OFF
#          -D ssdp=OFF
#          -D tools=OFF

      - name: Build
        run: cmake --build build

    # Step building core upnplib with GoogleTest
      - uses: actions/checkout@v2

      - name: Configure core upnplib with GoogleTest
        run: >
          cmake
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}
          -D GOOGLETEST=ON

      - name: Build
        run: cmake --build build

  macos:
    name: Job build (macos-latest) - ${{ matrix.conf }}
    runs-on: macos-latest

    strategy:
      matrix:
        conf: [Debug, Release]
      fail-fast: false

    steps:
    # Step building the core upnplib
      - uses: actions/checkout@v2

      - name: Install build tools
        run: brew install pkg-config cmake ninja

      - name: Configure
        run: >
          cmake
          -G Ninja
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}

      - name: Build
        run: cmake --build build

    # Step building the core upnplib with GoogleTest
      - uses: actions/checkout@v2

      - name: Install build tools
        run: brew install pkg-config cmake ninja

      - name: Configure
        run: >
          cmake
          -G Ninja
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}
          -D GOOGLETEST=ON

      - name: Build
        run: cmake --build build
