name: Build

on: [push, pull_request]

jobs:
  linux:
    name: Build (${{ matrix.os }}) - ${{ matrix.conf }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, uabuntu-20.04]
        conf: [Debug, Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}
          -D GOOGLETEST=ON
          -D BUILD_TESTING=OFF
          -D client=OFF
          -D device=OFF
          -D gena=OFF
          -D ipv6=OFF
          -D optssdp=OFF
          -D samples=OFF
          -D scriptsupport=OFF
          -D soap=OFF
          -D ssdp=OFF
          -D tools=OFF

      - name: Build
        run: cmake --build build

  macos:
    name: Build (${{ matrix.os }}) - ${{ matrix.conf }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest] # macos-10.15, macos-11.0
        conf: [Debug, Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install build tools
        run: brew install pkg-config cmake ninja

      - name: Configure
        run: >
          cmake
          -G Ninja
          -S .
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.conf }}
          -D GOOGLETEST=ON
          -D BUILD_TESTING=OFF
          -D client=OFF
          -D device=OFF
          -D gena=OFF
          -D ipv6=OFF
          -D optssdp=OFF
          -D samples=OFF
          -D scriptsupport=OFF
          -D soap=OFF
          -D ssdp=OFF
          -D tools=OFF

      - name: Build
        run: cmake --build build
